### ISSUE TITLE
{"message": "Endpoint request timed out"}

### ISSUE THREAD

**Issue by FiftyFour7250** [leokodish/mikashi#6]
I wanted to check it out, but it doesn't work. Authorization error(

![Снимок2](https://user-images.githubusercontent.com/78786088/110284911-85975500-7ff3-11eb-8d8b-201b086e7975.JPG)

**Comment by leokodish** [comment]
After looking into this, it appears that this can happen when trying to use Mikashi without playing music on Spotify. Although I do have routing for this situation, it looks like this can still happen. For now I would suggest making sure you are playing music through Spotify before trying to use Mikashi.
